import './global.css';
import { StyledComponentsRegistry } from './registry';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

export const metadata = {
  title: 'Welcome to demo2',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
